# Site settings
title: Diplomatura de Extensión en Desarrollo de Videojuegos
description: >- 
  Diplomatura de Extensión en Desarrollo de Videojuegos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://idei.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-minimal
description: Bookmark this to keep an eye on my project updates!

# Author information
author:
  name: Emilio
  email: eormeno@gmail.com

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Social media
social_links:
  github: idei
  twitter: # your-twitter-handle
  linkedin: # your-linkedin-username

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md